# Generated by Django 4.1.4 on 2024-02-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('vendeur', models.CharField(max_length=30)),
                ('prix', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=20)),
                ('emailClient', models.CharField(max_length=20)),
                ('passwordClient', models.CharField(max_length=20)),
                ('confirmationClient', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomVendeur', models.CharField(max_length=20)),
                ('emailVendeur', models.CharField(max_length=20)),
                ('passwordVendeur', models.CharField(max_length=20)),
                ('confirmationVendeur', models.CharField(max_length=20)),
                ('boutique', models.CharField(max_length=20)),
                ('abonnement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirmation', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.client')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.vendeur')),
            ],
        ),
    ]
